version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'logisnet'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my_db:/var/lib/mysql
    
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5490:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
  my_db: